//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoSachMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public int IdDanhMuc { get; set; }
        public string TheLoai { get; set; }
        public int IdKeSach { get; set; }
    
        public virtual KeSach KeSach { get; set; }
    }
}
