//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoSachMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoSach
    {
        public int IdKho { get; set; }
        public string TenKho { get; set; }
        public string TenNhanVien { get; set; }
        public int IdTKKho { get; set; }
        public int IdKiemKho { get; set; }
    
        public virtual KiemKeKho KiemKeKho { get; set; }
        public virtual ThongKeKho ThongKeKho { get; set; }
    }
}
