//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoSachMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KhoSachEntities : DbContext
    {
        public KhoSachEntities()
            : base("name=KhoSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<KeSach> KeSaches { get; set; }
        public virtual DbSet<KhoSach> KhoSaches { get; set; }
        public virtual DbSet<KiemKeKho> KiemKeKhoes { get; set; }
        public virtual DbSet<NhapKho> NhapKhoes { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongKeKho> ThongKeKhoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XuatKho> XuatKhoes { get; set; }
    }
}
