//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoSachMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongKeKho()
        {
            this.KhoSaches = new HashSet<KhoSach>();
        }
    
        public int IdTKKho { get; set; }
        public Nullable<System.DateTime> NgayTK { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public int IdSach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoSach> KhoSaches { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
